name: Run Deploy-Tests on Dev Branch

on:
  push: 
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Execute test script
      run: |
        bash deploy/deploy.Linux.sh -uv